package:
  name: cytnx
  version: "0.7a"

source:
  git_url: https://github.com/kaihsin/Cytnx.git

build:
  number: 0


requirements:
  build:
    - python {{ python }}
    - numpy >=1.18
    - cmake  
    - pybind11 
    - boost
    - mkl >=2019
    - mkl-include >=2019
    - intel-openmp
    - setuptools
    - python-graphviz
    - graphviz
    - blas * mkl
    - {{ compiler("c")}}
    - {{ compiler("cxx")}}

  host:
    - python 
    - numpy >=1.18
    - boost
    - mkl >=2019
    - mkl-include >=2019
    - intel-openmp
    - setuptools
    - python-graphviz
    - graphviz
    - blas * mkl

  run:
    - python 
    - numpy >=1.18
    - boost
    - mkl >=2019
    - mkl-include >=2019
    - intel-openmp
    - setuptools
    - python-graphviz
    - graphviz
    - blas * mkl

about:
