language: python

job:
  include:
    - os: linux
      python: 3.6
      env: TOXENV=py36
    - os: linux
      python: 3.7
      env: TOXENV=py37
    - os: osx
      language generic
      env: TOXENV=py37
      
install:
  - ./install_entry.sh

script:
  - conda activate test-environment
  - python --version
