language: python

jobs:
  include:
    - os: linux
      python: 3.6
      env: TOXENV=py36
      dist: bionic

    - os: linux
      python: 3.7
      env: TOXENV=py37
      dist: bionic

    - os: linux
      python: 3.8
      env: TOXENV=py38
      dist: bionic

    - os: osx
      language: generic
      env: TOXENV=py36

    - os: osx
      language: generic
      env: TOXENV=py37

    - os: osx
      language: generic
      env: TOXENV=py38
      
install:
  - ./install_conda.sh

script:
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - conda activate test-environment
  - python --version
  - ./conda_build.sh
  #- if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./conda_build_gpu.sh     ; fi
