name: Conda Build For Linux

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  BuildAndTest:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v3
    
    - name: Install miniconda3 and create env
      working-directory: ${{github.workspace}}
      run: |
        echo "Install miniconda---------------------------------"
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        bash miniconda.sh -b -p $HOME/minicondaL
        echo $HOME
        source $HOME/minicondaL/etc/profile.d/conda.sh
        conda info -a
    
    - name: Config Conda
      working-directory: ${{github.workspace}}
      run: |
        echo "Config Conda---------------------------------"
        source $HOME/minicondaL/etc/profile.d/conda.sh
        conda info -a

        hash -r
        conda config --set always_yes yes --set changeps1 no
        conda config --add channels conda-forge
        conda update -q conda
        conda update -q --all
        conda install anaconda-client conda-build

        #conda create -q -n test-enviroment python=3.10 anaconda-client conda-build _openmp_mutex=*=*_llvm
        #conda env list
        #conda run -n test-enviroment python --version

    - name: start building
      working-directory: ${{github.workspace}}
      run: |
        echo "Building begin---------------------------------"
        source $HOME/minicondaL/etc/profile.d/conda.sh
        #conda run -n test-enviroment python --version
        #conda run -n test-enviroment conda -h
        #conda run -n test-enviroment conda config --set anaconda_upload no
        conda config --set anaconda_upload no
        
        echo "Get Output file names:_________________" 
        OUTPUT_FN=$(conda-build conda_gen/ --output)
        
        echo "Start building---------------------------------"
        # building on env. 
        #conda build conda_gen/
        anaconda -h

    - name: Upload build
      working-directory: ${{github.workspace}}
      run: |
        #echo "Upload build---------------------------------"
        #source $HOME/minicondaL/etc/profile.d/conda.sh
        #conda run -n test-enviroment anaconda -t $CONDA_UPLOAD_TOKEN upload -u kaihsinwu $OUTPUT_FN --force
