name: Conda Build For MacOSX

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  BuildAndTest:
    runs-on: macos-12

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v3
    
    - name: Install miniconda3 and create env
      working-directory: ${{github.workspace}}
      run: |
        echo "Install miniconda---------------------------------"
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh
        bash miniconda.sh -b -p $HOME/minicondaL
        echo $HOME
        source $HOME/minicondaL/etc/profile.d/conda.sh
        conda info -a

    - name: Config Conda
      working-directory: ${{github.workspace}}
      run: |
        echo "Config Conda---------------------------------"

        source $HOME/minicondaL/etc/profile.d/conda.sh
        conda info -a

        hash -r
        conda config --set always_yes yes --set changeps1 no

        conda config --add channels conda-forge
        conda update -q conda
        conda update -q --all
        conda install anaconda-client conda-build
        $HOME/minicondaL/bin/anaconda -h


    - name: start building
      working-directory: ${{github.workspace}}
      run: |
        echo "Building begin---------------------------------"
        source $HOME/minicondaL/etc/profile.d/conda.sh
        conda config --set anaconda_upload no

        # these are infos used to check environ
        conda info -a
        conda list
        $HOME/minicondaL/bin/anaconda -h


        echo "Get Output file names:_________________"
        OUTPUT_FN=$(conda build conda_gen_mac/ --output)

        echo "Start building---------------------------------"
        conda build conda_gen_mac/

 
        echo "Upload build---------------------------------"
        source $HOME/minicondaL/etc/profile.d/conda.sh
        $HOME/minicondaL/bin/anaconda -t $TOKEN upload -u kaihsinwu $OUTPUT_FN --force
      env:
        TOKEN: ${{ secrets.CONDA_UPLOAD_TOKEN }}
