name: Conda Build For Linux

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  BuildAndTest:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Show conda info
      working-directory: ${{github.workspace}}
      run: |
        # Useful for debugging any issues with conda
        conda info -a
        
    - name: Upload build
      working-directory: ${{github.workspace}}
      run: |
        conda init bash
        conda create -q -n test-environment python=3.10 anaconda-client conda-build compilers
        conda activate test-environment
        conda config --set anaconda_upload no
        OUTPUT_FN=$(conda build conda_gen/ --output)
        conda build conda_gen/
        anaconda -t $CONDA_UPLOAD_TOKEN upload -u kaihsinwu $OUTPUT_FN --force
