name: Conda Build For MacOSX

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  BuildAndTest:
    runs-on: macos-12

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install Anaconda
      working-directory: ${{github.workspace}}
      run: |
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh
        bash miniconda.sh -b -p ${{github.workspace}}/miniconda
        echo ${{github.workspace}}
        source "${{github.workspace}}/miniconda/etc/profile.d/conda.sh"
        hash -r
        conda config --set always_yes yes --set changeps1 no
        conda config --add channels conda-forge 
        conda update --all
        # Useful for debugging any issues with conda
        conda info -a
        
    - name: Upload build
      working-directory: ${{github.workspace}}
      run: |
        source "${{github.workspace}}/miniconda/etc/profile.d/conda.sh"
        conda create -q -n test-environ python=3.10 anaconda-client conda-build
        conda activate test-environ
        # this is to check debug
        anaconda -h
        conda config --set anaconda_upload no
        OUTPUT_FN=$(conda build conda_gen/ --output)
        conda build conda_gen/
        anaconda -t $CONDA_UPLOAD_TOKEN upload -u kaihsinwu $OUTPUT_FN --force
