name: Conda Build For Linux

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  BuildAndTest:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      working-directory: ${{github.workspace}}
      run: |
        # Useful for debugging any issues with conda
        $CONDA/bin/conda info -a
        $CONDA/bin/conda config --add channels conda-forge
        $CONDA/bin/conda install python=3.10 anaconda-client conda-build
        $CONDA/bin/conda install -c conda-forge compilers

    - name: Upload build
      working-directory: ${{github.workspace}}
      run: |
        $CONDA/bin/conda config --set anaconda_upload no
        OUTPUT_FN=$(conda build conda_gen/ --output)
        $CONDA/bin/conda build conda_gen/
        anaconda -t $CONDA_UPLOAD_TOKEN upload -u kaihsinwu $OUTPUT_FN --force
