name: Conda Build For Linux

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  BuildAndTest:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v3
    
    - name: Install miniconda3 and create env
      working-directory: ${{github.workspace}}
      run: |
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        bash miniconda.sh -b -p $HOME/minicondaL
        echo $HOME
        source $HOME/minicondaL/etc/profile.d/conda.sh

    - name: Config conda
      working-directory: ${{github.workspace}}
      run: |
        hash -r
        conda config --set always_yes yes --set changeps1 no
        conda create -q -n test-environment python=3.10
        conda activate test-environment
        #conda update -q conda
        #conda info -a
        #conda create -q -n test-environment python=3.10 anaconda-client conda-build

    - name: Activate env and start building
      working-directory: ${{github.workspace}}
      run: |
        #conda activate test-enviroment
        #python --version 

    - name: Upload build
      working-directory: ${{github.workspace}}
      run: |
        #$CONDA/bin/conda init bash
        #conda activate test-environ
        #python --version
        #conda config --set anaconda_upload no
        #OUTPUT_FN=$(conda build conda_gen/ --output)
        #$CONDA/bin/conda build conda_gen/
        #anaconda -t $CONDA_UPLOAD_TOKEN upload -u kaihsinwu $OUTPUT_FN --force
